name: jd-scripts-docker

on:
  push:
    branches: 
    - master
  schedule:
    - cron: 5 0 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    name: JD Scripts

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Free disk space
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E snap set system refresh.retain=2
        sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
        [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Init dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y runc containerd docker docker.io docker-compose
        sudo -E apt-get clean -y
        df -h

    - name: Run Scripts
      run: |
        sudo systemctl enable docker
        sudo systemctl restart docker
        sudo docker-compose up --build --force-recreate --detach jd1
        sudo docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; node jd_bean_sign.js'
